---
- hosts: kvm
  gather_facts: no
  become: true
  become_user: root
  become_method: sudo

  vars_files:
    - "vars/params.yml"

  tasks:


    - name: generate a list of dictionary to create an ansible host
      command: python3 generateListDict.py vars/params.yml
      delegate_to: 127.0.0.1
      register: listPrivate

    - debug: var=listPrivate.stdout

    - set_fact:
        jsonListPrivate: "{{ listPrivate.stdout | from_json }}"

    - debug: var=jsonListPrivate

    - name: Create an ansible inventory host file for Avi controller(s)
      template:
        src: "{{ ansibleHost.privateTemplate }}"
        dest: "{{ item }}"
      delegate_to: 127.0.0.1
      ignore_errors: yes
      loop: "{{ ansibleHost.private }}"
