---
packageList:
  - qemu-kvm
  - libvirt-bin
  - ubuntu-vm-builder
  - bridge-utils
  - virtinst
  - python-lxml

kvm:
  username: avi
  networkTemplate: network.xml.j2
  domainTemplate: domain.xml.j2
  networks:
    - name: net1
      bridgeName: virbr1
      networkIp: 200.1.1.1
      networkMask: 255.255.255.0
  domains:
    - name: avi-controller1
      id: 1
      ip: 200.1.1.2
      mask: 255.255.255.0
      gw: 200.1.1.1

# uuid and mac address need to be variabilized

avi:
  controllerIpFile: avi_meta_controller.yml.j2
  localPathQcow2File: /home/avi/bin/avi/
  fileName: controller-17.2.14-9128.qcow2
  cpu: 6
  mem: 14336000

local:
  password: avi123
  routes:
    - cidr: 200.1.1.2/32
      nexthop: 192.168.17.151
